// Code generated by protoc-gen-zig
///! package head
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;
const json = protobuf.json;
const UnionDecodingError = protobuf.UnionDecodingError;

pub const PacketHead = struct {
    pb: protobuf.ProtobufMixins(@This()) = .{},
    packet_id: u32 = 0,
    ack_packet_id: u32 = 0,

    pub const _desc_table = .{
        .packet_id = fd(1, null, .{ .Varint = .Simple }),
        .ack_packet_id = fd(11, null, .{ .Varint = .Simple }),
    };
};
